### PR TITLE
Support RTSP configurable Range header

### PR DESCRIPTION
**Pull request by Jordy84**
Send `Range` RTSP header when source is RTSP and configuration options `rtspRangeType` & `rtspRangeStart` are configured.

### CODE REVIEW

**Comment by Jordy84** [comment]
In our application we need to set the Start time of a recording played back using a RTSP stream. This can be done using a Range header which is already supported in `gortsplib`. This PR makes this available in Mediamtx as well.

This is my first time working with Golang, so please be gentle ;)

Hopefully this can be added to Mediamtx so we don't have to use our own fork anymore in the future

**Comment by aler9** [comment]
Hello, this is very useful and it also solves issue #1096. Let me know when the PR is ready to be merged.

**Comment by Jordy84** [comment]
Thanks, I think it's ready. So please let me know if you think somethings need to change

**Comment by aler9** [comment]
i did some changes:
* i rebased the PR against main
* errors inside createRangeHeader() are now handled
* tests have been added
* API docs have been updated

this has been merged, thanks!

**Comment by Jordy84** [comment]
Thanks for merging this 👍

**Comment by aler9** [comment]
added in v0.23.0

**Pull request merged**
